### PR TITLE
Use dashed edges for aggregate

### LINKED ISSUE #27: Include aggregate?
Hi,

thanks for this plugin; really helps to give an overview over complex builds!

Currently it just considers classpath dependencies, ie, `dependsOn`, tho.  Could it also include task dependencies, ie, `aggregate`?  In a complex build setup this also helps to understand what gets build.

### PR DESCRIPTION
**Pull request by lunaryorn**
Closes #27.

Renders

spec_works

for the following project (see `spec/works`):

```sbt
lazy val foo = project in file(".") aggregate (a, b, c)

val a = project
val b = project dependsOn a
val c = project dependsOn b
```

### CODE REVIEW

**Comment by lunaryorn** [comment]
@dwijnand Looks like 0.13 results in a different order of dependencies in the Graph so Travis CI fails on 0.13.

Any idea what causes this?  How could I work around this issue in tests?  I'm not familiar with sbt-scripted.

**Comment by lunaryorn** [comment]
@dwijnand I updated the plugin build to SBT 1.1.5, and changed DOT output to sort nodes and edges first to make the DOT output stable, so `scripted` now runs on SBT 1.1 and 0.13.

**Comment by dwijnand** [comment]
That's properly amazing, @lunaryorn. I'm seriously impressed.

My only pushback was I prefer testing on minimal sbt versions. So I've pushed a commit to that effect, and I'm happy to merge this if Travis CI is happy with it.

**Comment by lunaryorn** [comment]
Thank you very much, I’m flattered 😊

Thank you very much for merging.  Would you mind to publish a new release?

**Comment by dwijnand** [comment]
Done! https://github.com/dwijnand/sbt-project-graph/releases/tag/v0.3.0

**Comment by lunaryorn** [comment]
@dwijnand Thanks :+1:

**Comment by lunaryorn** [comment]
Also for the invation.  Not sure how much I'll add, since my single most desired change is now in, but I'll keep an eye on it :heart:

**Comment by dwijnand** [comment]
It comes with no strings attached. If I get hit by a bus you can take over now. 😄

**Pull request merged**
